In [1]:
import pandas as pd

df = pd.read_csv('sales_dataset.csv', parse_dates=['Date'])

# Question 1: Total revenue by salesperson and date

q1 = df.pivot_table(index='Salesperson', columns='Date', values='Revenue', aggfunc='sum')
print("Q1: Total Revenue by Salesperson and Date\n", q1)

# Question 2: Average revenue per sale for each product

q2 = df.groupby('Product')['Revenue'].mean()
print("\nQ2: Average Revenue per Sale by Product\n", q2)

# Question 3: Max units sold in a single transaction by each salesperson

q3 = df.groupby('Salesperson')['Units Sold'].max()
print("\nQ3: Max Units Sold per Transaction by Salesperson\n", q3)

# Question 4: Percentage of total revenue by region

total_revenue = df['Revenue'].sum()
q4 = df.groupby('Region')['Revenue'].sum() / total_revenue * 100
print("\nQ4: Percentage of Total Revenue by Region\n", q4)

# Question 5: Salesperson with most transactions

q5 = df['Salesperson'].value_counts()
print("\nQ5: Number of Transactions per Salesperson\n", q5)

# Question 6: Pivot showing total revenue and units sold by salesperson and product

q6 = df.pivot_table(index='Salesperson', columns='Product', values=['Revenue', 'Units Sold'], aggfunc='sum')
print("\nQ6: Total Revenue and Units Sold by Salesperson and Product\n", q6)

# Question 7: Total units sold in each region on each date

q7 = df.pivot_table(index='Region', columns='Date', values='Units Sold', aggfunc='sum')
print("\nQ7: Total Units Sold by Region and Date\n", q7)

Q1: Total Revenue by Salesperson and Date
 Date         2024-01-01  2024-02-01  2024-03-01  2024-04-01  2024-05-01
Salesperson
Alice             200.0         NaN       240.0         NaN       270.0
Bob                 NaN       150.0       400.0         NaN         NaN
Charlie             NaN       300.0         NaN         NaN       300.0
David               NaN         NaN         NaN       240.0         NaN

Q2: Average Revenue per Sale by Product
 Product
Widget A    285.0
Widget B    240.0
Name: Revenue, dtype: float64

Q3: Max Units Sold per Transaction by Salesperson
 Salesperson
Alice      12
Bob        20
Charlie    15
David       8
Name: Units Sold, dtype: int64

Q4: Percentage of Total Revenue by Region
 Region
East     24.285714
North    35.714286
South    28.571429
West     11.428571
Name: Revenue, dtype: float64

Q5: Number of Transactions per Salesperson
 Alice      3
Bob        2
Charlie    2
David      1
Name: Salesperson, dtype: int64

Q6: Total Revenue and Units Sold by Salesperson and Product
              Revenue          Units Sold
Product     Widget A Widget B   Widget A Widget B
Salesperson
Alice          440.0    270.0       22.0      9.0
Bob            400.0    150.0       20.0      5.0
Charlie        300.0    300.0       15.0     10.0
David            NaN    240.0        NaN      8.0

Q7: Total Units Sold by Region and Date
 Date    2024-01-01  2024-02-01  2024-03-01  2024-04-01  2024-05-01
Region
East           NaN         NaN        12.0         NaN         9.0
North         10.0         5.0        20.0         NaN         NaN
South          NaN        15.0         NaN         NaN        10.0
West           NaN         NaN         NaN         8.0         NaN