In [1]:
import pandas as pd
sales_data = pd.read_csv('sales_data.csv')
feedback_data = pd.read_csv('customer_feedback.csv')

# Question 1: Hierarchical Index with Product and Month

sales_hierarchical = sales_data.set_index(['product', 'month'])
print("Q1: Hierarchical Index:\n", sales_hierarchical)

# Question 2: Merge using various joins on OrderID

inner_join = pd.merge(sales_data, feedback_data, on='orderID', how='inner')
print("\nQ2: Inner Join:\n", inner_join)

# Outer Join
outer_join = pd.merge(sales_data, feedback_data, on='orderID', how='outer')
print("\nQ2: Outer Join:\n", outer_join)

# Left Join
left_join = pd.merge(sales_data, feedback_data, on='orderID', how='left')
print("\nQ2: Left Join:\n", left_join)

# Right Join
right_join = pd.merge(sales_data, feedback_data, on='orderID', how='right')
print("\nQ2: Right Join:\n", right_join)

# Question 3: Concatenate Sales DataFrames

q1 = sales_data.iloc[0:2]
q2 = sales_data.iloc[2:4]
q3 = sales_data.iloc[4:]

# Vertical Concatenation
vertical_concat = pd.concat([q1, q2, q3], axis=0)
print("\nQ3: Vertical Concatenation:\n", vertical_concat)

# Horizontal Concatenation
horizontal_concat = pd.concat([q1.reset_index(drop=True), q2.reset_index(drop=True)], axis=1)
print("\nQ3: Horizontal Concatenation:\n", horizontal_concat)

# Question 4: Function to combine and fill missing feedback_score

def combine_and_fill_feedback(sales_df, feedback_df):
    merged = pd.merge(sales_df, feedback_df, on='orderID', how='outer')
    merged['feedback_score'] = merged['feedback_score'].fillna(method='ffill')
    return merged

combined_filled = combine_and_fill_feedback(sales_data, feedback_data)
print("\nQ4: Combined and Filled Feedback:\n", combined_filled)

# Question 5: Pivot Sales Data by Month

def pivot_sales_by_month(sales_df):
    pivot = sales_df.pivot_table(
        index='product',
        columns='month',
        values='sales',
        aggfunc='sum'
    ).fillna(0)
    return pivot

pivot_table = pivot_sales_by_month(sales_data)
print("\nQ5: Pivot Table:\n", pivot_table)

Q1: Hierarchical Index:
                   orderID  sales
product month
A       January         1    250
B       February        2    300
A       February        3    200
C       March           4    400
A       March           5    150

Q2: Inner Join:
    orderID product   month_x  sales  customer_ID   month_y  feedback_score
0        1       A   January    250          101   January             4.5
1        2       B  February    300          102  February             4.0

Q2: Outer Join:
    orderID product   month_x  sales  customer_ID   month_y  feedback_score
0        1       A   January  250.0        101.0   January             4.5
1        2       B  February  300.0        102.0  February             4.0
2        3       A  February  200.0          NaN       NaN             NaN
3        4       C     March  400.0          NaN       NaN             NaN
4        5       A     March  150.0          NaN       NaN             NaN
5        6     NaN       NaN    NaN        103.0  February             3.5
6        7     NaN       NaN    NaN        104.0     March             5.0
7        8     NaN       NaN    NaN        105.0     March             4.8

Q2: Left Join:
    orderID product   month_x  sales  customer_ID   month_y  feedback_score
0        1       A   January    250        101.0   January             4.5
1        2       B  February    300        102.0  February             4.0
2        3       A  February    200          NaN       NaN             NaN
3        4       C     March    400          NaN       NaN             NaN
4        5       A     March    150          NaN       NaN             NaN

Q2: Right Join:
    orderID product   month_x  sales  customer_ID   month_y  feedback_score
0        1       A   January  250.0          101   January             4.5
1        2       B  February  300.0          102  February             4.0
2        6     NaN       NaN    NaN          103  February             3.5
3        7     NaN       NaN    NaN          104     March             5.0
4        8     NaN       NaN    NaN          105     March             4.8

Q3: Vertical Concatenation:
    orderID product     month  sales
0        1       A   January    250
1        2       B  February    300
2        3       A  February    200
3        4       C     March    400
4        5       A     March    150

Q3: Horizontal Concatenation:
    orderID product     month  sales  orderID product     month  sales
0        1       A   January    250        3       A  February    200
1        2       B  February    300        4       C     March    400

Q4: Combined and Filled Feedback:
    orderID product   month_x  sales  customer_ID   month_y  feedback_score
0        1       A   January  250.0        101.0   January             4.5
1        2       B  February  300.0        102.0  February             4.0
2        3       A  February  200.0          NaN       NaN             4.0
3        4       C     March  400.0          NaN       NaN             4.0
4        5       A     March  150.0          NaN       NaN             4.0
5        6     NaN       NaN    NaN        103.0  February             3.5
6        7     NaN       NaN    NaN        104.0     March             5.0
7        8     NaN       NaN    NaN        105.0     March             4.8

Q5: Pivot Table:
 month    February  January  March
product
A           200.0    250.0  150.0
B           300.0      0.0    0.0
C             0.0      0.0  400.0